[theme]
primaryColor = "#0B1F3B"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "sans serif"  # Inter / Source Sans 3 loaded via CSS

[layout]
widescreen = true
